search_words = [
        {'baza': "szukam",
         'przypadek': "gen",
         'nadpisz': {}
        },
        {'baza': "chciałbym",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "chcę",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "polecisz mi",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "masz może",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "może",
         'przypadek': "nom",
         'nadpisz': {}
        },
        {'baza': "może być",
         'przypadek': "nom",
         'nadpisz': {"liczba": 'sg'}
        },
        {'baza': "potrzebuję",
         'przypadek': "gen",
         'nadpisz': {}
        },
        {'baza': "chcę",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "poleć mi",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "daj mi",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "poleć",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "daj",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "chciałabym",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "znajdź",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "znajdź mi",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "weź mi daj",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "weź mi poleć",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "zaproponuj",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "zapodaj",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "zapodaj mi",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "zaproponuj mi",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "no to",
         'przypadek': "nom",
         'nadpisz': {}
        },
        {'baza': "niech będzie",
         'przypadek': "nom",
         'nadpisz': {"liczba": 'sg'}
        },
        {'baza': "niech będą",
         'przypadek': "nom",
         'nadpisz': {"liczba": 'pl'}
        }
    ]

document_types = [
            {'baza': "coś", 'odmiana': False, 'dozwolone_po': ['gen','acc', 'nom'], 'nadpisz': {'przypadek': 'gen', 'liczba': 'sg', 'rodzaj': 'n'}},
            {'baza': "czegoś", 'odmiana': False, 'dozwolone_po': ['gen'], 'nadpisz': {'przypadek': 'gen', 'liczba': 'sg', 'rodzaj': 'n'}},
            {'baza': "dokument", 'odmiana': True, 'dozwolone_po': ['gen','acc','nom'], 'nadpisz': {}},
            {'baza': "książka", 'odmiana': True, 'dozwolone_po': ['gen','acc','nom'], 'nadpisz': {}},
            {'baza': "artykuł", 'odmiana': True, 'dozwolone_po': ['gen','acc','nom'], 'nadpisz': {}},
            {'baza': "praca", 'odmiana': True, 'dozwolone_po': ['gen','acc','nom'], 'nadpisz': {}},
            {'baza': "rozprawa", 'odmiana': True, 'dozwolone_po': ['gen','acc','nom'], 'nadpisz': {}},
            {'baza': "recenzja", 'odmiana': True, 'dozwolone_po': ['gen','acc','nom'], 'nadpisz': {}},
            {'baza': "esej", 'odmiana': True, 'dozwolone_po': ['gen','acc','nom'], 'nadpisz': {}},
            {'baza': "patent", 'odmiana': True, 'dozwolone_po': ['gen','acc','nom'], 'nadpisz': {}},
            {'baza': "norma", 'odmiana': True, 'dozwolone_po': ['gen','acc','nom'], 'nadpisz': {}},
            {'baza': "skrypt", 'odmiana': True, 'dozwolone_po': ['gen','acc','nom'], 'nadpisz': {}},
            {'baza': "publikacja", 'odmiana': True, 'dozwolone_po': ['gen','acc','nom'], 'nadpisz': {}},
            {'baza': "podręcznik", 'odmiana': True, 'dozwolone_po': ['gen','acc','nom'], 'nadpisz': {}},
            {'baza': "encyklopedia", 'odmiana': True, 'dozwolone_po': ['gen','acc','nom'], 'nadpisz': {}}
]

zaw_words = [
    {'baza': "zawierać",
     'odmiana': True,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : False,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["elementy", "tematykę", "problematykę", "wyjaśnienie", "informacje", ":"],
     'fleksem': 'pact',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'acc'
    },
    {'baza': "obejmować",
     'odmiana': True,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : False,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja':["tematykę", "problematykę", "dziedzinę", "wyjaśnienie", ":"],
     'fleksem': 'pact',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'acc'
    },
    {'baza': "tyczyć",
     'odmiana': True,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : True,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja':["się"],
     'fleksem': 'pact',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'gen'
    },
    {'baza': "omawiać",
     'odmiana': True,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : False,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja':["tematykę","temat","problematykę","problem", ":"],
     'fleksem': 'pact',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'acc'
    },
    {'baza': "opisywać",
     'odmiana': True,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : False,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["tematykę","temat","problem","problematykę", ":"],
     'fleksem': 'pact',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'acc'
    },
    {'baza': "wyjaśniać",
     'odmiana': True,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : False,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["tematykę","temat","problem","problematykę", ":"],
     'fleksem': 'pact',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'acc'
    },
    {'baza': "mówić",
     'odmiana': True,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : True,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["o"],
     'fleksem': 'pact',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'dat'
    },
    {'baza': "odnosić",
     'odmiana': True,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : True,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["się do"],
     'fleksem': 'pact',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'gen'
    },
    {'baza': "o",
     'odmiana': False,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : False,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["tagu","tagach","tematyce","temacie", "problemie","problematyce", "motywie", ":"],
     'fleksem': '',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'dat'
    },
    {'baza': "dotyczyć",
     'odmiana': True,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : False,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["tematu", "tematyki", "problematyki", ":"],
     'fleksem': 'pact',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'gen'
    },
    {'baza': "na",
     'odmiana': False,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : True,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["temat"],
     'fleksem': '',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'gen'
    },
    {'baza': "poświęcić",
     'odmiana': True,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : False,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["tematyce", "problemowi", "problematyce"],
     'fleksem': 'ppas',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'dat'
    },
    {'baza': "z",
     'odmiana': False,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : False,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["elementami","dziedziny","motywem", ":"],
     'fleksem': '',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'inst'
    },
    {'baza': "mieć",
     'odmiana': True,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : False,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["związek z", "elementy", "tagi", "tag"],
     'fleksem': 'pact',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'acc'
    },
    {'baza': "posiadać",
     'odmiana': True,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : False,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["elementy", "tagi", "tag", "wyjaśnienie", ":"],
     'fleksem': 'pact',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'acc'
    },
    {'baza': "odnośnie",
     'odmiana': False,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : False,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["tematu", "tematyki", "kwestii", ":"],
     'fleksem': '',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'gen'
    },
    {'baza': "w",
     'odmiana': False,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : True,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["tematyce","dziedzinie", "zakresie", "branży", "kwestii"] ,
     'fleksem': '',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'acc'
    },
    {'baza': "związać",
     'odmiana': True,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : True,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["z"],
     'fleksem': 'ppas',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : 'inst'
    },
    {'baza': "który",
     'odmiana': True,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : True,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["zawiera","opisuje","porusza","informuje", "wyjaśni","poinformuje", "wyjaśni"],
     'fleksem': 'adj',
     'nadpisz': {'przypadek': "nom"},
     'dozwolone_po': ["not", "coś", "czegoś"],
     'przypadek' : ''
    },
    {'baza': "co",
     'odmiana': False,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : True,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["zawiera","opisuje","porusza","informuje", "wyjaśnia","poinformuje", "wyjaśni"],
     'fleksem': 'adj',
     'nadpisz': {'przypadek': "nom"},
     'dozwolone_po': ["only", "coś", "czegoś"],
     'przypadek' : ''
    },
    {'baza': "informować",
     'odmiana': True,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : True,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["o", "na"],
     'fleksem': 'pact',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : ''
    },
    {'baza': "mającego",
     'odmiana': False,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : True,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["związek", "informacje", "informację"],
     'fleksem': 'pact',
     'nadpisz': {},
     'dozwolone_po': ["only", "coś", "czegoś"],
     'przypadek' : ''
    },
    {'baza': "poruszać",
     'odmiana': True,
     'potrzebny_przed' : '',
     'potrzebna_kontynuacja' : True,
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["tematykę", "problematykę"],
     'fleksem': 'pact',
     'nadpisz': {},
     'dozwolone_po': ["all"],
     'przypadek' : ''
    },
    {'baza': "który",
     'odmiana': True,
     'potrzebna_kontynuacja' : True,
     'potrzebny_przed' : 'w',
     'możliwa_kontynuacja' : True,
     'moz_kontynuacja': ["znajdę", "są", "jest"],
     'fleksem': 'adj',
     'nadpisz': {'przypadek': 'loc', 'liczba': 'sg'},
     'dozwolone_po': ["all"],
     'przypadek' : ''
    },
]

con_syn = [
    {'baza': "elementy",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["takie jak", "związane z", "z", ":"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },
    {'baza': "tematykę",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["związaną z", "z"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },
    {'baza': "problematykę",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["związaną z", "z"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "związaną z",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["tematem", "problemem", "dziedziną", "branżą"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'inst'
     },
    {'baza': "związane z",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["tematem", "problemem", "dziedziną", "branżą"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'inst'
     },
    {'baza': "wyjaśnienie",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["problemu", "tematu", "problematyki"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },
    {'baza': "się",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["tematu", "problemu", "problematyki"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },
    {'baza': "się do",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["tematu", "problemu", "problematyki"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },
    {'baza': "problem",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "o",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["temacie", "problemie"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'dat'
     },
    {'baza': "tagu",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'nom'
     },
    {'baza': "tagach",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["takich jak", ":"],
     'konieczna_mnoga': True,
     'możliwa_mnoga': True,
     'przypadek': 'nom'
     },
    {'baza': "tematyce",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "temacie",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "problemie",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "problematyce",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "motywie",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "problemowi",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "elementami",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },
    {'baza': "motywem",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "dziedziny",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "związek z",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ['tematem', 'dziedziną', 'problemem'],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'inst'
     },
    {'baza': "tagi",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["takie jak", ":"],
     'konieczna_mnoga': True,
     'możliwa_mnoga': True,
     'przypadek': 'nom'
     },
    {'baza': "tag",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "kwestii",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },
    {'baza': "dziedzinie",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "zakresie",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "branży",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "zawiera",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["elementy", "element", "informacje", "informację", "wyjaśnienie", ":"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'nom'
     },
    {'baza': "opisuje",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["problem", "problematykę", "temat", "tematykę"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'acc'
     },
    {'baza': "porusza",
     'odmiana': False,
     'potrzebna_kontynuacja': True,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["problem", "temat"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'acc'
     },
    {'baza': "informuje",
     'odmiana': False,
     'potrzebna_kontynuacja': True,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["o", "na"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'dat'
     },
    {'baza': "wyjaśnia",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["problem", "problematykę"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'acc'
     },
    {'baza': "poinformuje",
     'odmiana': False,
     'potrzebna_kontynuacja': True,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["mnie"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'dat'
     },
    {'baza': "wyjaśni",
     'odmiana': False,
     'potrzebna_kontynuacja': True,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["mi"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'dat'
     },
    {'baza': "mi",
     'odmiana': False,
     'potrzebna_kontynuacja': True,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["problem", "temat", "tematykę"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },
    {'baza': "mnie",
     'odmiana': False,
     'potrzebna_kontynuacja': True,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["o", "na"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },
    {'baza': "na",
     'odmiana': False,
     'potrzebna_kontynuacja': True,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["temat"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },
    {'baza': "temat",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "takie jak",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': [":"],
     'przypadek': 'nom'
     },
    {'baza': "takich jak",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': [":"],
     'konieczna_mnoga': True,
     'możliwa_mnoga': True,
     'przypadek': 'nom'
     },
    {'baza': "z",
     'odmiana': False,
     'potrzebna_kontynuacja': True,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["tematem", "problemem", "dziedziną"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },
    {'baza': "problemem",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "tematem",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "dziedziną",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "element",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "tematyki",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },
    {'baza': "branżą",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "dziedzinę",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "tematu",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "problematyki",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "problemu",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "informacje",
     'odmiana': False,
     'potrzebna_kontynuacja': True,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["o", "na", "z dziedziny", "z tematu"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },
    {'baza': "znajdę",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["wiedzę", "informacje", "informację", "omówienie"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'acc'
     },
    {'baza': "wiedzę",
     'odmiana': False,
     'potrzebna_kontynuacja': True,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["o", "na"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },
    {'baza': "są",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["informacje", ":"],
     'konieczna_mnoga': True,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },
    {'baza': "z dziedziny",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "z tematu",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "jest",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["wiedza", "informacja"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'nom'
     },
    {'baza': "informacja",
     'odmiana': False,
     'potrzebna_kontynuacja': True,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["z", "o"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "informację",
     'odmiana': False,
     'potrzebna_kontynuacja': True,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["z", "o"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "omówienie",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["tematu", "problemu"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': False,
     'przypadek': 'gen'
     },
    {'baza': "wiedza",
     'odmiana': False,
     'potrzebna_kontynuacja': True,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["z tematu", "z dziedziny", "o", "na"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },
    {'baza': "związek",
     'odmiana': False,
     'potrzebna_kontynuacja': True,
     'możliwa_kontynuacja': True,
     'moz_kontynuacja': ["z"],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },
    {'baza': ":",
     'odmiana': False,
     'potrzebna_kontynuacja': False,
     'możliwa_kontynuacja': False,
     'moz_kontynuacja': [],
     'konieczna_mnoga': False,
     'możliwa_mnoga': True,
     'przypadek': 'gen'
     },

]

aut_syn = ["autorstwa", "napisany przez", "której autorem jest", "którego twórcą"]

dodaj_voc = [
        {'baza': "dodatkowo",
         'przypadek': "nom",
         'nadpisz': {}
        },
        {'baza': "no to",
         'przypadek': "nom",
         'nadpisz': {}
        },
        {'baza': "no to dodatkowo",
         'przypadek': "nom",
         'nadpisz': {}
        },
        {'baza': "no to niech będzie",
         'przypadek': "nom",
         'nadpisz': {"liczba": 'sg'}
        },
        {'baza': "no to niech będą",
         'przypadek': "nom",
         'nadpisz': {"liczba": 'pl'}
        },
        {'baza': "no to wybieram",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "no to wolę",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "no to już niech będzie",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "niech będzie",
         'przypadek': "nom",
         'nadpisz': {"liczba": 'sg'}
        },
        {'baza': "niech już będzie",
         'przypadek': "nom",
         'nadpisz': {"liczba": 'sg'}
        },
        {'baza': "niech będą",
         'przypadek': "nom",
         'nadpisz': {"liczba": 'pl'}
        },
        {'baza': "niech już będą",
         'przypadek': "nom",
         'nadpisz': {"liczba": 'pl'}
        },
        {'baza': "wybieram",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "wolę",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "już bym wolał",
         'przypadek': "acc",
         'nadpisz': {}
        },
        {'baza': "może być",
         'przypadek': "acc",
         'nadpisz': {"liczba": 'sg'}
        },
        {'baza': "no to może być",
         'przypadek': "acc",
         'nadpisz': {"liczba": 'sg'}
        },
        {'baza': "mogą być",
         'przypadek': "acc",
         'nadpisz': {"liczba": 'pl'}
        },
        {'baza': "no to mogą być",
         'przypadek': "acc",
         'nadpisz': {"liczba": 'pl'}
        },
        {'baza': "bardziej",
         'przypadek': "nom",
         'nadpisz': {}
        },
        {'baza': "bardziej pasuje mi",
         'przypadek': "nom",
         'nadpisz': {}
        },
        {'baza': "dodatkowo wybieram",
         'przypadek': "nom",
         'nadpisz': {}
        },
        {'baza': "bardziej interesuje mnie",
         'przypadek': "nom",
         'nadpisz': {}
        },
        {'baza': "jestem bardziej zainteresowany",
         'przypadek': "acc",
         'nadpisz': {}
        }
]